CC = gcc
CFLAGS = -Wall -g
BUILD = reading ASCIIIO lineNumberingPrinter

all: $(BUILD)

clean:
	/bin/rm -f $(BUILD) *.o core *~

reading: reading.o

ASCIIIO: ASCIIIO.o

lineNumberingPrinter: lineNumberingPrinter.o
